### PR TITLE
Let Resources designer fix inclusion of resources

### LINKED ISSUE #7661: [NBug] Could not find any resources appropriate for the specified ...
## Current behaviour
Switching to console tab or running any processes fail.

## Expected behaviour
Console works like it did in release/3.3

## Steps to reproduce

1. Checkout release/3.3
1. Clean working directory
1. Run Setup\build.cmd Debug
1. Run the git extensions program that was built.
1. Switch to console tab
1. Note it works
1. Checkout this commit and repeat steps
1. Note you get an app crash

## Error Details
```
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "ConEmu.WinForms.Resources.resources" was correctly embedded or linked into assembly "ConEmuWinForms" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
   at ConEmu.WinForms.Resources.get_ConEmuSettingsTemplate()
   at ConEmu.WinForms.ConEmuStartInfo.get_BaseConfiguration()
   at GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__210_0(Object sender, TabControlCancelEventArgs args)
   at System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Somewhere between release/3.3 and 56b6a09ea7d245809a119f51554a091c4dd324f1 The console is broken

## Environment
- Git Extensions 3.3.0
- Build 56b6a09ea7d245809a119f51554a091c4dd324f1
- Git 2.25.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

### PR DESCRIPTION
**Pull request by vbjay**
fixes https://github.com/gitextensions/gitextensions/issues/7661

### CODE REVIEW

**Comment by vbjay** [comment]
Builds fine when building Git Extensions.  Will look at tonight.

**Review by gerhardol — APPROVED** [review]
Works for me
PR in gitextensions/gitextensions#7665

**Comment by vbjay** [comment]
@gerhardol @RussKie please fix the build.

https://ci.appveyor.com/project/RussKie/conemu-inside/history

**Comment by RussKie** [comment]
I'll accept a PR if GE builds

**Comment by gerhardol** [comment]
The ConEmu builds in AppVeyor has not been working for at least a year (I tested an old commit).
So build problem is not new, even if there are more errors after SDK style was merged.

ConEmu is often give exceptions on me lately, but this started before this PR and obviously before SDK style that broke ConEmu completely.

Even if not perfect, this PR should be merged to make master usable again, it is developer usage that finds an improves most functionality.

**Comment by RussKie** [comment]
Thank you for the PR. but it wasn't quite correct.
I have fixed in 368f663340b7fbd99d6f8013be0562593988455a

**Pull request closed without merging**
